-- 코드를 입력하세요

SELECT A.ID AS ID , A.NAME AS NAME , A.HOST_ID AS HOST_ID
FROM PLACES A LEFT JOIN 
(
SELECT COUNT(*) as C , HOST_ID
FROM PLACES
GROUP BY HOST_ID
) B ON A.HOST_ID = B.HOST_ID
WHERE B.C > 1
ORDER BY ID