-- 코드를 입력하세요

SELECT FLAVOR

FROM (
    SELECT FH.FLAVOR, FH.TOTAL_ORDER + J.TOTAL_ORDER AS TOTAL_ORDER

    FROM (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM FIRST_HALF
        GROUP BY FLAVOR
        ) AS FH
        INNER JOIN 
        (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
        ) AS J
        ON FH.FLAVOR = J.FLAVOR
    ) FINAL

ORDER BY TOTAL_ORDER DESC

LIMIT 3