-- 코드를 작성해주세요


SELECT B.YEAR, (A.MAX - B.SIZE_OF_COLONY) AS YEAR_DEV , B.ID
FROM (
    SELECT MAX(SIZE_OF_COLONY) AS MAX , YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR
    ) AS A JOIN 
    (
    SELECT ID,SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    ) AS B ON A.YEAR = B.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC