SELECT DISTINCT A.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A INNER JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
WHERE A.START_DATE >= '2022-10-01' AND A.START_DATE < '2022-11-01' AND B.CAR_TYPE = '세단'
ORDER BY A.CAR_ID DESC